name: poc_seo
description: A new jaspr project.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
     sdk: flutter
  jaspr: ^0.16.2
  jaspr_flutter_embed: ^0.4.2
  jaspr_router: ^0.6.0
  http: ^1.2.2

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.0.10+1
  jaspr_builder: ^0.16.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  jaspr_lints: ^0.1.2

jaspr:
  mode: server

flutter:
  uses-material-design: true
