name: Build app
run-name: running
on: 
 workflow_dispatch:
env:
  API_TOKEN: ${{ secrets.API_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.24.5
    - run: flutter --version
    - run: dart pub global activate jaspr_cli
    - run: jaspr build
    - name: upload build
      uses: actions/upload-artifact@v4
      with:
        name: build-result
        path: build/